const buttons = [
  { code: 'Backquote', en: '`' },
  { code: 'Digit1', en: '1' },
  { code: 'Digit2', en: '2' },
  { code: 'Digit3', en: '3' },
  { code: 'Digit4', en: '4' },
  { code: 'Digit5', en: '5' },
  { code: 'Digit6', en: '6' },
  { code: 'Digit7', en: '7' },
  { code: 'Digit8', en: '8' },
  { code: 'Digit9', en: '9' },
  { code: 'Digit0', en: '0' },
  { code: 'Minus', en: '-' },
  { code: 'Equal', en: '=' },
  { code: 'Backspace', en: 'Backspace', classNames: ['btn-backspace'] },
  { code: 'Tab', en: 'Tab', classNames: ['btn-tab'] },
  { code: 'KeyQ', en: 'q', ru: 'й' },
  { code: 'KeyW', en: 'w', ru: 'ц' },
  { code: 'KeyE', en: 'e', ru: 'у' },
  { code: 'KeyR', en: 'r', ru: 'к' },
  { code: 'KeyT', en: 't', ru: 'е' },
  { code: 'KeyY', en: 'y', ru: 'н' },
  { code: 'KeyU', en: 'u', ru: 'г' },
  { code: 'KeyI', en: 'i', ru: 'ш' },
  { code: 'KeyO', en: 'o', ru: 'щ' },
  { code: 'KeyP', en: 'p', ru: 'з' },
  { code: 'BracketLeft', en: '[', ru: 'х' },
  { code: 'BracketRight', en: ']', ru: 'ъ' },
  { code: 'Backslash', en: '\\' },
  { code: 'Delete', en: 'Del', classNames: ['btn-del'] },
  { code: 'CapsLock', en: 'CapsLock', classNames: ['btn-caps'] },
  { code: 'KeyA', en: 'a', ru: 'ф' },
  { code: 'KeyS', en: 's', ru: 'ы' },
  { code: 'KeyD', en: 'd', ru: 'в' },
  { code: 'KeyF', en: 'f', ru: 'а' },
  { code: 'KeyG', en: 'g', ru: 'п' },
  { code: 'KeyH', en: 'h', ru: 'р' },
  { code: 'KeyJ', en: 'j', ru: 'о' },
  { code: 'KeyK', en: 'k', ru: 'л' },
  { code: 'KeyL', en: 'l', ru: 'д' },
  { code: 'Semicolon', en: ';', ru: 'ж' },
  { code: 'Quote', en: "'", ru: 'э' },
  { code: 'Enter', en: 'Enter', classNames: ['btn-enter'] },
  { code: 'ShiftLeft', en: 'Shift', classNames: ['btn-shift', 'btn-shift_left'] },
  { code: 'KeyZ', en: 'z', ru: 'я' },
  { code: 'KeyX', en: 'x', ru: 'ч' },
  { code: 'KeyC', en: 'c', ru: 'с' },
  { code: 'KeyV', en: 'v', ru: 'м' },
  { code: 'KeyB', en: 'b', ru: 'и' },
  { code: 'KeyN', en: 'n', ru: 'т' },
  { code: 'KeyM', en: 'm', ru: 'ь' },
  { code: 'Comma', en: ',', ru: 'б' },
  { code: 'Period', en: '.', ru: 'ю' },
  { code: 'Slash', en: '/', ru: '.' },
  { code: 'ArrowUp', en: '&#9650;', classNames: ['btn-arrow', 'btn-arrow_up'] },
  { code: 'ShiftRight', en: 'Shift', classNames: ['btn-shift', 'btn-shift_right'] },
  { code: 'ControlLeft', en: 'Ctrl', classNames: ['btn-ctrl', 'btn-ctrl_left'] },
  { code: 'MetaLeft', en: 'Win' },
  { code: 'AltLeft', en: 'Alt' },
  { code: 'Space', en: ' ', classNames: ['btn-space'] },
  { code: 'AltRight', en: 'Alt' },
  { code: 'ArrowLeft', en: '&#9668;', classNames: ['btn-arrow', 'btn-arrow_left'] },
  { code: 'ArrowDown', en: '&#9660;', classNames: ['btn-arrow', 'btn-arrow_down'] },
  { code: 'ArrowRight', en: '&#9658;', classNames: ['btn-arrow', 'btn-arrow_right'] },
  { code: 'ControlRight', en: 'Ctrl', classNames: ['btn-ctrl', 'btn-ctrl_right'] },
];

export default buttons;
